name: Basic CI

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "Repo is empty, but CI/CD workflow is running!"
